/// @return {Array<Enum.POKER_HANDS>}
function get_poker_hands_array() {
	static _poker_hands = [
		POKER_HANDS.HIGH_CARD,
		POKER_HANDS.PAIR,
		POKER_HANDS.TWO_PAIRS,
		POKER_HANDS.THREE_OF_A_KIND,
		POKER_HANDS.STRAIGHT,
		POKER_HANDS.FLUSH,
		POKER_HANDS.FULL_HOUSE,
		POKER_HANDS.FOUR_OF_A_KIND,
		POKER_HANDS.STRAIGHT_FLUSH,
		POKER_HANDS.FIVE_OF_A_KIND,
		POKER_HANDS.FLUSH_HOUSE,
		POKER_HANDS.FLUSH_FIVE,
	]
	
	return _poker_hands
}